### ISSUE TITLE
Documentation about React

### ISSUE THREAD

**Issue by UO257192** [Arquisoft/viade_es2c#2]
# Documentation about React
We have to research about react for front-end:
- React Official documentation.
- Blogs.
- Video tutorials.

**Comment by jaimeknd77** [comment]
Download link of Node.js:
https://nodejs.org/en/

We are going to use 12.14.1 LTS because we have more information in order to solve future problems.

https://nodejs.org/dist/v12.14.1/node-v12.14.1-x64.msi

**Comment by jaimeknd77** [comment]
Tutorial about how to start in React:

https://reactjs.org/tutorial/tutorial.html

**Comment by UO257192** [comment]
# Some examples

## Solid React app generator
https://github.com/inrupt/generator-solid-react/blob/develop/README.md

## ReactJS
- https://es.reactjs.org/
- https://github.com/reactjs/reactjs.org/blob/master/README.md

## ReactNative
https://facebook.github.io/react-native/docs/getting-started

## Bootstrap
https://getbootstrap.com/docs/4.1/getting-started/introduction/

**Comment by jaimeknd77** [comment]
### Differences between React and React Native
The article explains business advantages of using React and the business advantages of using React Native
https://www.cognitiveclouds.com/insights/what-is-the-difference-between-react-js-and-react-native/
