### ISSUE TITLE
Documentation about Solid 

### ISSUE THREAD

**Issue by UO264872** [Arquisoft/viade_es2c#4]
Basic concepts about solid and react apps

https://solid.inrupt.com/docs/writing-solid-apps-with-react
https://github.com/Inrupt-inc/solid-react-components

**Comment by AnaGciaSchz** [comment]
Some interesting pages About SOLID

- [SOLID for non-geek users](https://forum.solidproject.org/t/solid-for-non-geek-users-why-how-and-what-s-next/392)

- [SOLID chat on gitter](https://gitter.im/solid/chat)

- [Introduction for SOLID](https://solidproject.org/for-developers/apps/first-app)

- [SOLID forum](https://forum.solidproject.org/)

**Comment by AnaGciaSchz** [comment]
I've been researching about how to upload files into a POD and found some interesting pages for the future (now we are working on the demo, so we can do a simple functionality now)

- [Solid-File-Client](https://github.com/jeff-zucker/solid-file-client)
- [Solid-File-Client demo](https://jeff-zucker.github.io/solid-file-client/docs/examples/)
- [How can my app handle data from a solid pod](https://forum.solidproject.org/t/how-can-my-app-handle-data-from-a-solid-pod/1787/4)
- [Ldflex](https://github.com/solid/query-ldflex) (We already agreed on using it, but I'll link the repository)
