### ISSUE TITLE
Library seach

### ISSUE THREAD

**Issue by AnaGciaSchz** [Arquisoft/viade_es2c#5]
We need to investigate about some React and Solid libraries so we can start thinking about how we are going to develop our viade app.

**Comment by AnaGciaSchz** [comment]
During my investigation, I found a few interesting pages:

- [At this page](https://forum.solidproject.org/t/openchakra-a-visual-react-builder/2639) we find a post on the solid project forum where a user talks about a visual editor for react based on SOLID UI. It doesn't exist at the moment but a solution can be using 'OpenChakra', a visual editor for React based on Chakra UI. Maybe we can use it in our project.

- [Here](https://forum.solidproject.org/t/best-js-libraries-to-help-build-visualisation-components-of-rdf-using-sveltejs/2548)  I found a post with some js libraries related to RDF that we might like to see in the future.

- [JS library for managing SOLID files and folders](https://forum.solidproject.org/t/solid-file-client-a-library-for-solid-files-folders/465)

- [React components for SOLID](https://github.com/solid/react-components)

**Comment by jaimeknd77** [comment]
### React Burger Menu

React Burger Menu provides you with a sidebar with a large number of effects and styles through CSS transitions. It supports many animations such as slide, stack, bubble, push and many more. Use the new features of CSS3, so there are animations that will not display well in all browsers.

**Comment by jaimeknd77** [comment]
### React Google Map

Reaction component based on the Google Maps API. It is completely isomorphic and allows you to represent animated reaction components on the map, even if the Google Maps API has not been loaded. Thanks to its algorithm, all objects on the map can be made hover.

**Comment by UO257192** [comment]
### React Photo Gallery

React responsive and super customizable image gallery. Maintains the aspect ratio of your photos and uses elements of real images. It is also possible to pass your image components to add additional features, such as legends and favorites.
https://github.com/neptunian/react-photo-gallery

**Comment by UO257192** [comment]
### React Notification System
React component fully customizable to implement notifications on your website. Through its properties you can define a title, a message, the position, the action and much more. For optimal appearance, this component should be represented in a higher level HTML element in your application to avoid positional conflicts.
https://github.com/igorprado/react-notification-system

**Comment by UO257192** [comment]
### React Native
For develop phone apps.
https://facebook.github.io/react-native/

**Comment by AnaGciaSchz** [comment]
**sparqlFiddle**
To use sarql in our app:
https://github.com/jeff-zucker/sparql-fiddle

**Solid-File-Client**
https://github.com/jeff-zucker/solid-file-client

**Other libraries**
The react solid template base that we used includes a lot of libraries to use
https://github.com/inrupt/generator-solid-react
